# Generated by Django 4.2.7 on 2024-09-17 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_expedition_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climber',
            options={'verbose_name': 'Альпинист', 'verbose_name_plural': 'Альпинисты'},
        ),
        migrations.AlterModelOptions(
            name='expedition',
            options={'ordering': ('-date_formation',), 'verbose_name': 'Экспедиция', 'verbose_name_plural': 'Экспедиции'},
        ),
        migrations.AlterField(
            model_name='expedition',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 17, 18, 20, 21, 33562, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
