# Generated by Django 4.2.7 on 2024-09-18 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_climberexpedition_climber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 18, 5, 14, 30, 971895, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
